[package]
name = "nabob-metrics-core"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
prometheus = { workspace = true }

[dev-dependencies]
claims = { workspace = true }
