[package]
name = "nabob-config"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
nabob-crypto = { workspace = true }
nabob-global-constants = { workspace = true }
nabob-logger = { workspace = true }
nabob-secure-storage = { workspace = true }
nabob-short-hex-str = { workspace = true }
nabob-temppath = { workspace = true }
nabob-types = { workspace = true }
arr_macro = { workspace = true }
bcs = { workspace = true }
byteorder = { workspace = true }
cfg-if = { workspace = true }
get_if_addrs = { workspace = true }
maplit = { workspace = true }
num_cpus = { workspace = true }
poem-openapi = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_merge = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[dev-dependencies]
nabob-crypto = { workspace = true }
nabob-types = { workspace = true, features = ["fuzzing"] }
tempfile = { workspace = true }

[features]
default = []
failpoints = []
fuzzing = ["nabob-crypto/fuzzing", "nabob-types/fuzzing"]
smoke-test = []
testing = []
tokio-console = []
