[package]
name = "nabob-layered-map"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
ahash = { workspace = true }
nabob-crypto = { workspace = true }
nabob-drop-helper = { workspace = true }
nabob-infallible = { workspace = true }
nabob-metrics-core = { workspace = true }
bitvec = "1.0.1"
itertools = { workspace = true }
once_cell = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
nabob-schemadb = { workspace = true }
nabob-temppath = { workspace = true }
criterion = { workspace = true }
itertools = { workspace = true }
jemallocator = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }
rocksdb = { workspace = true }

[lib]
bench = false
