[package]
name = "Event example"
version = "0.0.1"

[addresses]
std = "0x1"
nabob_framework = "0x1"
event = "_"

[dependencies]
NabobFramework = { git = "https://github.com/nabob-labs/nabob-framework.git", subdir = "nabob-framework", rev = "main" }
