[package]
name = "nabob-scratchpad"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
nabob-crypto = { workspace = true }
nabob-drop-helper = { workspace = true }
nabob-infallible = { workspace = true }
nabob-metrics-core = { workspace = true }
nabob-types = { workspace = true }
nabob-vm = { workspace = true }
bitvec = { workspace = true }
criterion = { workspace = true, optional = true }
dashmap = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
proptest = { workspace = true, optional = true }
rayon = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
nabob-types = { workspace = true, features = ["fuzzing"] }
bitvec = { workspace = true }
once_cell = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }

[target.'cfg(unix)'.dev-dependencies]
jemallocator = { workspace = true }

[features]
fuzzing = ["nabob-types/fuzzing", "proptest"]
bench = ["proptest", "criterion"]

[lib]
# Allow Criterion benchmarks to take command line arguments
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false
