[package]
name = "nabob-indexer-grpc-server-framework"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
nabob-metrics-core = { workspace = true }
async-trait = { workspace = true }
backtrace = { workspace = true }
clap = { workspace = true }
figment = { workspace = true }
prometheus = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
warp = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
nabob-system-utils = { workspace = true }
