[package]
name = "move-command-line-common"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
difference = { workspace = true }
dirs-next = { workspace = true }
hex = { workspace = true }
move-core-types = { workspace = true }
num-bigint = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }
walkdir = { workspace = true }
