[package]
name = 'knight'
version = '1.0.0'

[addresses]
knight = "_"

[dependencies]
NabobFramework = { git = "https://github.com/nabob-labs/nabob-framework.git", subdir = "nabob-framework", rev = "main" }
NabobTokenObjects = { git = "https://github.com/nabob-labs/nabob-framework.git", subdir = "nabob-token-objects", rev = "main" }
