[package]
name = "nabob-vm-genesis"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
nabob-cached-packages =  { workspace = true }
nabob-crypto = { workspace = true }
nabob-framework =  { workspace = true }
nabob-gas-schedule = { workspace = true }
nabob-types = { workspace = true }
nabob-vm = { workspace = true }
nabob-vm-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
claims = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
nabob-proptest-helpers = { workspace = true }
move-core-types = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }

[features]
default = []
fuzzing = ["nabob-types/fuzzing", "move-core-types/fuzzing", "move-vm-types/fuzzing"]
