[package]
name = "move-bytecode-spec"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
once_cell = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lib]
proc-macro = true
