[package]
name = "move-resource-viewer"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
move-binary-format = { workspace = true }
move-bytecode-utils = { workspace = true }
move-core-types = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }

anyhow = { workspace = true }
hex = { workspace = true }
