[package]
name = "Hero"
version = "0.0.0"

[addresses]
hero = "_"

[dependencies]
NabobFramework = { git = "https://github.com/nabob-labs/nabob-framework.git", subdir = "nabob-framework", rev = "main" }
NabobTokenObjects = { git = "https://github.com/nabob-labs/nabob-framework.git", subdir = "nabob-token-objects", rev = "main" }
