[package]
name = "nabob-language-e2e-tests"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
nabob-abstract-gas-usage = { workspace = true }
nabob-bitvec = { workspace = true }
nabob-block-executor = { workspace = true }
nabob-cached-packages ={ workspace = true }
nabob-crypto = { workspace = true, features = ["fuzzing"] }
nabob-framework = { workspace = true }
nabob-gas-algebra = { workspace = true }
nabob-gas-meter = { workspace = true }
nabob-gas-profiling = { workspace = true }
nabob-gas-schedule = { workspace = true }
nabob-keygen = { workspace = true }
nabob-proptest-helpers = { workspace = true }
nabob-temppath = { workspace = true }
nabob-types = { workspace = true }
nabob-vm = { workspace = true }
nabob-vm-environment = { workspace = true }
nabob-vm-genesis = { workspace = true }
nabob-vm-logging = { workspace = true }
nabob-vm-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
claims = { workspace = true }
goldenfile = { workspace = true }
move-binary-format = { workspace = true }
move-command-line-common = { workspace = true }
move-core-types = { workspace = true, features = ["fuzzing"] }
move-ir-compiler = { workspace = true }
move-model = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
petgraph = "0.5.1"
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }

[features]
default = []
fuzzing = []
