[package]
name = "nabob-speculative-state-helper"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

# Do NOT add any inter-project dependencies.
# This is to avoid ever having a circular dependency with the nabob-speculative crate.
[dependencies]
anyhow = { workspace = true }
nabob-infallible = { workspace = true }
crossbeam = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
claims = { workspace = true }
parking_lot = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
