[package]
name = "nabob-db"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
nabob-accumulator = { workspace = true }
nabob-config = { workspace = true }
nabob-crypto = { workspace = true }
nabob-db-indexer = { workspace = true }
nabob-db-indexer-schemas = { workspace = true, features = ["fuzzing"] }
nabob-executor-types = { workspace = true }
nabob-runtimes-extension = { workspace = true }
nabob-infallible = { workspace = true }
nabob-jellyfish-merkle = { workspace = true }
nabob-logger = { workspace = true }
nabob-metrics-core = { workspace = true }
nabob-proptest-helpers = { workspace = true, optional = true }
nabob-resource-viewer = { workspace = true }
nabob-rocksdb-options = { workspace = true }
nabob-schemadb = { workspace = true }
nabob-scratchpad = { workspace = true }
nabob-storage-interface = { workspace = true, features = ["fuzzing"] }
nabob-temppath = { workspace = true, optional = true }
nabob-types = { workspace = true }
arc-swap = { workspace = true }
arr_macro = { workspace = true }
bcs = { workspace = true }
byteorder = { workspace = true }
claims = { workspace = true }
clap = { workspace = true, optional = true }
crossbeam-channel = { workspace = true, optional = true }
dashmap = { workspace = true }
either = { workspace = true }
hex = { workspace = true }
indicatif = { workspace = true, optional = true }
itertools = { workspace = true }
lru = { workspace = true }
move-core-types = { workspace = true }
once_cell = { workspace = true }
owo-colors = { workspace = true, optional = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
rayon = { workspace = true }
serde = { workspace = true }
static_assertions = { workspace = true }
status-line = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
nabob-executor-types = { workspace = true }
nabob-jellyfish-merkle = { workspace = true, features = ["fuzzing"] }
nabob-proptest-helpers = { workspace = true }
nabob-schemadb = { workspace = true, features = ["fuzzing"] }
nabob-scratchpad = { workspace = true, features = ["fuzzing"] }
nabob-temppath = { workspace = true }
nabob-types = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "nabob-proptest-helpers", "nabob-temppath", "nabob-crypto/fuzzing", "nabob-jellyfish-merkle/fuzzing", "nabob-types/fuzzing", "nabob-executor-types/fuzzing", "nabob-schemadb/fuzzing", "nabob-scratchpad/fuzzing"]
consensus-only-perf-test = []
db-debugger = ["nabob-temppath", "clap", "crossbeam-channel", "owo-colors", "indicatif"]
