[package]
name = "nabob-backup-cli"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
nabob-backup-svc = { workspace = true }
nabob-config = { workspace = true }
nabob-crypto = { workspace = true }
nabob-db = { workspace = true }
nabob-db-indexer-schemas = { workspace = true }
nabob-executor = { workspace = true }
nabob-executor-test-helpers = { workspace = true }
nabob-executor-types = { workspace = true }
nabob-indexer-grpc-table-info = { workspace = true }
nabob-infallible = { workspace = true }
nabob-jellyfish-merkle = { workspace = true }
nabob-logger = { workspace = true }
nabob-metrics-core = { workspace = true }
nabob-proptest-helpers = { workspace = true }
nabob-push-metrics = { workspace = true }
nabob-storage-interface = { workspace = true }
nabob-temppath = { workspace = true }
nabob-types = { workspace = true }
nabob-vm = { workspace = true }
nabob-vm-environment = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
csv = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-verifier = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
pin-project = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-io-timeout = { workspace = true }
tokio-stream = { workspace = true, features = ["fs"] }
tokio-util = { workspace = true }

[dev-dependencies]
nabob-backup-svc = { workspace = true }
nabob-config = { workspace = true }
nabob-db = { workspace = true }
nabob-executor-test-helpers = { workspace = true }
nabob-proptest-helpers = { workspace = true }
nabob-storage-interface = { workspace = true }
proptest = { workspace = true }
warp = { workspace = true }

[features]
testing = []
fuzzing = ["nabob-db/fuzzing"]
