[package]
name = "move-package"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
colored = { workspace = true }
itertools = { workspace = true }
move-abigen = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-source-map = { workspace = true }
move-bytecode-utils = { workspace = true }
move-command-line-common = { workspace = true }
move-compiler = { workspace = true }
move-compiler-v2 = { workspace = true }
move-core-types = { workspace = true }
move-docgen = { workspace = true }
move-model = { workspace = true }
move-symbol-pool = { workspace = true }
named-lock = { workspace = true }
once_cell = { workspace = true }
petgraph = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
tempfile = { workspace = true }
termcolor = { workspace = true }
toml = { workspace = true }
walkdir = { workspace = true }
whoami = { workspace = true }

[dev-dependencies]
datatest-stable = { workspace = true }
move-stdlib = { workspace = true }
