[package]
name = "nabob-vm-environment"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
nabob-framework = { workspace = true }
nabob-gas-algebra = { workspace = true }
nabob-gas-schedule = { workspace = true }
nabob-move-stdlib = { workspace = true }
nabob-native-interface = { workspace = true }
nabob-table-natives = { workspace = true }
nabob-types = { workspace = true }
nabob-vm-types = { workspace = true }
bcs = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-verifier = { workspace = true }
move-core-types = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
once_cell = { workspace = true }
sha3 = { workspace = true }

[dev-dependencies]
nabob-types = { workspace = true, features = ["testing", "fuzzing"] }
serde = { workspace = true }
