[package]
name = "nabob-validator-interface"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
nabob-api-types = { workspace = true }
nabob-config = { workspace = true }
nabob-db = { workspace = true }
nabob-framework = { workspace = true }
nabob-rest-cli = { workspace = true }
nabob-storage-interface = { workspace = true }
nabob-types = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
lru = { workspace = true }
move-core-types = { workspace = true }
tokio = { workspace = true }
