[package]
name = "nabob-api-types"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
nabob-config = { workspace = true }
nabob-crypto = { workspace = true }
nabob-framework = { workspace = true }
nabob-logger = { workspace = true }
nabob-openapi = { workspace = true }
nabob-resource-viewer = { workspace = true }
nabob-storage-interface = { workspace = true }
nabob-types = { workspace = true }
nabob-vm = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
hex = { workspace = true }
indoc = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
once_cell = { workspace = true }
poem = { workspace = true }
poem-openapi = { workspace = true }
poem-openapi-derive = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["async-trait", "poem", "poem-openapi-derive"]
