[package]
name = "nabob-genesis"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
nabob-cached-packages = { workspace = true }
nabob-config = { workspace = true }
nabob-crypto = { workspace = true }
nabob-db = { workspace = true }
nabob-executor = { workspace = true }
nabob-framework = { workspace = true }
nabob-keygen = { workspace = true }
nabob-logger = { workspace = true }
nabob-storage-interface = { workspace = true }
nabob-temppath = { workspace = true }
nabob-types = { workspace = true }
nabob-vm = { workspace = true }
nabob-vm-genesis = { workspace = true }
bcs = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }

[dev-dependencies]
nabob-config = { workspace = true }

[features]
testing = []
fuzzing = ["nabob-config/fuzzing"]
