[package]
name = "nabob-move-hashmap"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
nabob-aggregator = { workspace = true }
nabob-crypto = { workspace = true }
nabob-types = { workspace = true }
nabob-vm-types = { workspace = true }
bytes = { workspace = true }
claims = { workspace = true }
crossbeam = { workspace = true }
dashmap = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
nabob-aggregator = { workspace = true, features = ["testing"] }
move-vm-runtime = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rayon = { workspace = true }
test-case = { workspace = true }
