[package]
name = "nabob-validator-txpool"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
nabob-channels = { workspace = true }
nabob-crypto = { workspace = true }
nabob-infallible = { workspace = true }
nabob-types = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
nabob-types = { workspace = true, features = ["fuzzing"] }

[features]
fuzzing = []
